### ISSUE TITLE
cl-lsp path problem with remote development 

### ISSUE THREAD

**Issue by jing-bi** [ailisp/commonlisp-vscode#11]
when I try to use the extension on my remote server. It keeps showing:
`The terminal process failed to launch: Path to shell executable "cl-lsp" does not exist.`

I've tried to change the path to the absolute path on the server, but it's still not working.

I have the `export PATH="$HOME/.roswell/bin:$PATH"` in my bashrc file and I can call cl-lsp directly from the remote terminal.

I really appreciate your work on this extension!

Could you please tell me how to get this right?

**Comment by ailisp** [comment]
I just figured out I made a place wrong, that cause this extension requires cl-lsp in path. it's fixed in 0.3.2, simply upgrade will fix it!
As for your question specifically, it's because vscode took path in`~/.profile`, but not bashrc.
