### ISSUE TITLE
How do you select from the autocomplete list with the keyboard?

### ISSUE THREAD

**Issue by Lucretia** [ailisp/commonlisp-vscode#12]
Pressing return doesn't work, it just takes the cursor to the next line, doesn't select and insert the identifier like it should. I have to use the mouse to select, which does work, it's annoying.

**Comment by ailisp** [comment]
Hi @Lucretia, as all other auto completion in vscode, you can press arrow up/and down to locate desired item, and press <Tab> to autocomplete

**Comment by Lucretia** [comment]
I wouldn't have asked if it was that simple, would I? Don't you think I tried the usual ctrl+space to autocomplete?
