### ISSUE TITLE
This extension can't works on vscode for WSL2.

### ISSUE THREAD

**Issue by minghu6** [ailisp/commonlisp-vscode#3]
I have installed all the requirements according to the README guide.
But when I open the common lisp source project, the error message continuously popup (very crazy,  blind my eyes).
The error message said:

     The terminal process faild to launch... because `cl-lsp` not found
 (I can't read its content carefully for my eyes have got blind by fastly continuously popup)

However `~/.roswell/bin/` are included in $PATH and I can run `cl-lsp` directly on shell.

**Comment by ailisp** [comment]
Hi @minghu6 Sorry somehow I didn't get email notifications.

> However ~/.roswell/bin/ are included in $PATH and I can run cl-lsp directly on shell.

Do you have in ~/.profile, as reported by another people if it's sourced in ~/.bashrc it won't be in PATH at time of **vscode starts**
Alternatively you can set full path to cl-lsp here, and that should always work:
![image](https://user-images.githubusercontent.com/13259400/90093817-41540880-dce1-11ea-9004-1a539ce79b02.png)

**Comment by minghu6** [comment]
Yes, all works fine after export PATH in ~/.profile and restart WSL shell.

**Comment by ailisp** [comment]
Great!
