### ISSUE TITLE
FYI Ceramic: Writing Electron Apps in Common Lisp

### ISSUE THREAD

**Issue by snunez1** [ailisp/commonlisp-vscode#8]
Just an FYI: The [ceramic project](http://ceramic.github.io/) claims to allow one to write Electron apps in Common Lisp. Thought it might be useful here.

**Comment by ailisp** [comment]
Thanks for sharing! It's not directly helped here. Although vscode was a electron app, it has its own set of typescript API to create extensions,  which is used by this plugin
