### ISSUE TITLE
Should print statements show in the repl?

### ISSUE THREAD

**Issue by smashedtoatoms** [ailisp/commonlisp-vscode#9]
When I run a simple hello world function that writes to stdout I get a void response, which is expected since the function returns nothing. What is surprising is that I don't see the output. I see it in sly on emacs. Any ideas on what might be going on?

Great work, by the way. I'm so excited for this project!

**Comment by ailisp** [comment]
@smashedtoatoms Thanks! What is your code and expected behavior? For me, print print to a popup box at botton right of the UI:
![Screenshot from 2020-12-09 14-39-55](https://user-images.githubusercontent.com/13259400/101697329-7fadca00-3a2c-11eb-8686-717407b10a04.png)

**Comment by ailisp** [comment]
I guess i got what's you expected:
![Screenshot from 2020-12-09 14-42-14](https://user-images.githubusercontent.com/13259400/101697488-c7345600-3a2c-11eb-9bb3-96605f32f178.png)
I didn't use sly, but slime gives a similar effect, result is both print to REPL, and "popup" in the minibuffer

**Comment by smashedtoatoms** [comment]
You know, it's working fine now.  I re-installed vscode because unrelated things were acting weird, and it seems to have fixed everything.
